version: "2"
checks:
  similar-code:
    config:
      threshold: 200
plugins:
  tslint:
    enabled: true
    config: tslint.json
exclude_patterns:
  - "**/node_modules/"
  - "lib/"
  - "scripts/"
  - "tests/"
  - "**/*.d.ts"
  - "**/*.stories.*"
  - "**/*.test.*"
